backend:
  name: github
  repo: RyzenG/Catalogo-Amazonia   # <— tu repo
  branch: main
  base_url: https://catalogoamazonia.netlify.app
  auth_endpoint: /api/auth

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "paginas"
    label: "Páginas"
    files:
      - file: "index.html"
        label: "Página principal"
        name: "home"
        fields:
          - { label: "Título", name: "title", widget: "string", required: false }
          - { label: "Contenido", name: "body", widget: "markdown", required: false }
