backend:
  name: github
  repo: RyzenG/Catalogo-Amazonia   # tu repo
  branch: main
  base_url: https://catalogoamazonia.netlify.app
  auth_endpoint: /api/auth

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "productos"
    label: "Productos"
    folder: "content/productos"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nombre", name: "name", widget: "string" }
      - { label: "Precio", name: "price", widget: "number" }
      - { label: "Descripción", name: "desc", widget: "text" }
      - { label: "Imagen", name: "image", widget: "image" }
