
backend:
  name: github
  repo: RyzenG/Catalogo-Amazonia
  branch: main
  base_url: https://catalogoamazonia.netlify.app
  auth_endpoint: api/auth

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "productos"
    label: "Productos"
    folder: "content/productos"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Descripción", name: "description", widget: "text"}
      - {label: "Precio", name: "price", widget: "number"}
      - {label: "Imagen", name: "image", widget: "image"}
